apiVersion: v2
appVersion: '1.0'
description: A Helm chart for sptribs-frontend App
name: sptribs-frontend
home: https://github.com/hmcts/sptribs-frontend
version: 0.0.17
dependencies:
  - name: nodejs
    version: 2.4.14
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
  - name: idam-pr
    version: 2.2.7
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
    condition: idam-pr.enabled
