nodejs:
  applicationPort: 4000
  aadIdentityName: sptribs
  ingressHost: sptribs-frontend.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/sptribs/frontend:latest'

  environment:
    NODE_ENV: production
    REFORM_TEAM: sptribs
    REFORM_SERVICE_NAME: sptribs-frontend
    NODE_TLS_REJECT_UNAUTHORIZED: 0
    SERVICE_AUTH_PROVIDER_URL: 'http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'
    IDAM_WEB_URL: 'https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/login'
    IDAM_API_URL: 'https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/token'
    REDIS_HOST: 'sptribs-{{ .Values.global.environment }}.redis.cache.windows.net'
    EQUALITY_URL: 'https://pcq.{{ .Values.global.environment }}.platform.hmcts.net'
    PCQ_ENABLED: true

  keyVaults:
    sptribs:
      secrets:
        - idam-ui-secret
        - idam-systemupdate-username
        - idam-systemupdate-password
        - redis-access-key
        - s2s-secret
        - app-insights-instrumentation-key
        - postcode-lookup-token
idam-pr:
  enabled: false
