nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

  environment:
      CASE_API_URL: https://sptribs-case-api-pr-${CHANGE_ID}.preview.platform.hmcts.net

idam-pr:
  enabled: true
  redirect_uris:
    sptribs-frontend:
      - https://${SERVICE_FQDN}/receiver
