nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

  environment:
    PCQ_ENABLED: true
    RATE_LIMITER_DISABLED: true

  keyVaults:
    sptribs:
      secrets:
        - name: app-insights-instrumentation-key-preview
          alias: app-insights-instrumentation-key
        - name: app-insights-connection-string-preview
          alias: app-insights-connection-string

idam-pr:
  enabled: true
  redirect_uris:
    sptribs-frontend:
      - https://${SERVICE_FQDN}/receiver
