uploadTimeout: UPLOAD_TIMEOUT
services:
  authProvider:
    url: SERVICE_AUTH_PROVIDER_URL
    secret: SERVICE_AUTH_SECRET
  ccd:
    url: CCD_API_URL
  cdam:
    url: CASE_DOCUMENT_API_URL
  idam:
    authorizationURL: IDAM_WEB_URL
    tokenURL: IDAM_API_URL
    clientID: IDAM_CLIENT_ID
    clientSecret: IDAM_SECRET
  case:
    url: CCD_URL
  payments:
    url: PAYMENTS_API_URL
  feeLookup:
    url: FEE_LOOKUP_URL
  equalityAndDiversity:
    url: EQUALITY_URL
    tokenKey: PCQ_TOKEN
    enabled: PCQ_ENABLED
  dssUpdate:
    url: DSS_UPDATE_URL
port: PORT
session:
  redis:
    host: REDIS_HOST
e2e:
  userTestPassword: TEST_PASSWORD
appInsights:
  instrumentationKey: APPINSIGHTS_KEY
caseType: CASE_TYPE
jurisdiction: JURISDICTION
