security:
  referrerPolicy: 'origin'
port: 4000
timeout: 200000
services:
  authProvider:
    url: 'http://rpe-service-auth-provider-aat.service.core-compute-aat.internal'
    microservice: 'sptribs_frontend'
    secret: 'NEED TO INSERT SECRET'
  idam:
    authorizationURL: 'https://idam-web-public.aat.platform.hmcts.net/login'
    tokenURL: 'https://idam-api.aat.platform.hmcts.net/o/token'
    clientID: 'sptribs-frontend'
    clientSecret: 'NEED TO INSERT SECRET'
    systemUsername: 'dummy_user'
    systemPassword: 'dummy_password'
  sptribs:
    url: 'http://sptribs-case-api-aat.service.core-compute-aat.internal'
  equalityAndDiversity:
    url: 'https://pcq.aat.platform.hmcts.net'
    path: '/service-endpoint'
    tokenKey: 'NEED TO INSERT SECRET'
  postcodeLookup:
    url: 'https://api.os.uk/search/places/v1'
    token: 'NEED TO INSERT SECRET'
  fisDssUpdate:
    url: 'https://dss-update-case.aat.platform.hmcts.net/dss-update/start'
  hmctsHomePage:
    url: 'https://www.gov.uk/government/organisations/hm-courts-and-tribunals-service'
  RPE_TOKEN:
    url: 'http://rpe-service-auth-provider-aat.service.core-compute-aat.internal'
health:
  timeout: 5000
  deadline: 15000
session:
  secret: 'local'
  redis:
    host:
    key:
e2e:
  userTestPassword: ''
appInsights:
  instrumentationKey:
documentUpload:
  validation:
    totaldocuments: 5
    totalSupportingDocuments: 5
    totalAdditionalDocuments: 20
    totalOtherInformation: 20
    sizeInBytes: 524288000
queryParamsforApp:
  query:
    CIC: 'CIC'
cookies:
  expiryTime: 365
dynatrace:
  dynatraceUrl: 'https://js-cdn.dynatrace.com/jstag/17177a07246/bf24054dsx/eaee1077d24f66ab_complete.js'
